# Checks that a pull request can build the Verdict jars
#  - Runs code analysis scan too

name: Verdict continuous build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 11 ]
        os: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out VERDICT source
      uses: actions/checkout@v2

    - name: Set up CodeQL for scanning
      uses: github/codeql-action/init@v1
      with:
        languages: java

    - name: Set up GraphViz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ matrix.os }}-m2

    - name: Run Maven build
      run: mvn -B package -Dtycho.localArtifacts=ignore --file tools/pom.xml
      env:
        GraphVizPath: /usr/bin

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v1
