# Builds a Verdict release for developers on each push to master:
# - Uploads native binaries as build artifacts
# - Pushes verdict-dev Docker image to Docker Hub
# - Updates verdict-dev update site

name: Verdict main build

on:
  push:
    branches: [ master ]
    tags-ignore: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java-version: [ 8 ]
        ocaml-version: [ 4.07.1 ]
        os: [ macos-10.15, ubuntu-20.04 ]
        include:
          - os: macos-10.15
            zmq_install: brew install zmq
          - os: ubuntu-20.04
            zmq_install: sudo apt-get install -y libzmq3-dev

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out VERDICT source
      uses: actions/checkout@v2

    - name: Set up GraphViz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ matrix.os }}-m2

    - name: Run Maven build
      run: mvn -B package -Dtycho.localArtifacts=ignore --file tools/pom.xml
      env:
        GraphVizPath: /usr/bin

    - name: Check out kind2 source
      uses: actions/checkout@v2
      with:
        repository: kind2-mc/kind2
        path: tools/verdict-back-ends/kind2

    - name: Cache opam repository
      uses: actions/cache@v2
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-opam-${{ matrix.ocaml-version }}

    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}

    - name: Set up zmq library
      run: ${{ matrix.zmq_install }}

    - name: Install opam packages
      run: |
        opam install --yes \
          async \
          core \
          core_extended \
          dune \
          dune-build-info \
          menhir \
          ocamlbuild \
          ocamlfind \
          printbox \
          xml-light \
          yojson \
          zmq

    - name: Build aadl2iml
      run: |
        cd tools/verdict-back-ends/aadl2iml
        opam exec make

    - name: Build kind2
      run: |
        cd tools/verdict-back-ends/kind2
        opam exec make

    - name: Build soteria_pp
      run: |
        cd tools/verdict-back-ends/soteria_pp
        opam exec make

    - name: Upload aadl2iml
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binaries
        path: tools/verdict-back-ends/aadl2iml/bin/aadl2iml

    - name: Upload kind2
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binaries
        path: tools/verdict-back-ends/kind2/bin/kind2

    - name: Upload soteria_pp
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binaries
        path: tools/verdict-back-ends/soteria_pp/bin/soteria_pp

    - name: Upload verdict-bundle-app
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binaries
        path: tools/verdict-back-ends/verdict-bundle/verdict-bundle-app/target/verdict-bundle-app-1.0.0-SNAPSHOT-capsule.jar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push verdict-dev image
      uses: docker/build-push-action@v2
      with:
        context: tools/verdict-back-ends
        file: tools/verdict-back-ends/Dockerfile
        push: true
        cache-from: type=registry,ref=gehighassurance/verdict-dev:latest
        cache-to: type=inline
        tags: gehighassurance/verdict-dev:latest

    - name: Check out VERDICT-update-sites
      uses: actions/checkout@v2
      with:
        repository: ge-high-assurance/VERDICT-update-sites
        token: ${{ secrets.CI_PAT }}
        path: VERDICT-update-sites

    - name: Update verdict-dev in VERDICT-update-sites
      run: |
        cd VERDICT-update-sites
        rm -rf verdict-dev
        mv ../tools/verdict/com.ge.research.osate.verdict.updatesite/target/repository verdict-dev
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update verdict-dev in VERDICT-update-sites"
        git push
