# Builds a Verdict release for end users:
# - Uploads native binaries as build artifacts
# - Uploads extern.zip and README.md as GitHub release assets
# - Pushes verdict Docker image to Docker Hub
# - Updates verdict-latest and verdict-$RELEASE update sites

name: Verdict release build

on:
  release:
    types: [ published ]

jobs:
  native-binaries:
    strategy:
      matrix:
        ocaml-version: [ 4.07.1 ]
        os: [ macos-10.15, ubuntu-20.04 ]
        include:
          - os: macos-10.15
            zmq_install: brew install zmq
          - os: ubuntu-20.04
            zmq_install: sudo apt-get install -y libzmq3-dev

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out VERDICT source
      uses: actions/checkout@v2

    - name: Check out kind2 source
      uses: actions/checkout@v2
      with:
        repository: kind2-mc/kind2
        path: tools/verdict-back-ends/kind2

    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}

    - name: Set up zmq library
      run: ${{ matrix.zmq_install }}

    - name: Cache opam repository
      uses: actions/cache@v2
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-opam-${{ matrix.ocaml-version }}

    - name: Install opam packages
      run: |
        opam install --yes \
          async \
          core \
          core_extended \
          dune \
          dune-build-info \
          menhir \
          ocamlbuild \
          ocamlfind \
          printbox \
          xml-light \
          yojson \
          zmq

    - name: Build aadl2iml
      run: |
        cd tools/verdict-back-ends/aadl2iml
        opam exec make

    - name: Build kind2
      run: |
        cd tools/verdict-back-ends/kind2
        opam exec make

    - name: Build soteria_pp
      run: |
        cd tools/verdict-back-ends/soteria_pp
        opam exec make

    - name: Upload aadl2iml
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binaries
        path: tools/verdict-back-ends/aadl2iml/bin/aadl2iml

    - name: Upload kind2
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binaries
        path: tools/verdict-back-ends/kind2/bin/kind2

    - name: Upload soteria_pp
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binaries
        path: tools/verdict-back-ends/soteria_pp/bin/soteria_pp

  release:
    strategy:
      matrix:
        java-version: [ 8 ]
        os: [ ubuntu-20.04 ]

    needs: native-binaries
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out VERDICT source
      uses: actions/checkout@v2

    - name: Set up GraphViz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ matrix.os }}-m2

    - name: Run Maven build
      run: mvn -B package -Dtycho.localArtifacts=ignore --file tools/pom.xml
      env:
        GraphVizPath: /usr/bin

    - name: Download mac binaries
      uses: actions/download-artifact@v2
      with:
        name: macos-10.15-binaries
        path: extern/mac

    - name: Download nix binaries
      uses: actions/download-artifact@v2
      with:
        name: ubuntu-20.04-binaries
        path: extern/nix

    - name: Assemble extern folder
      run: |
        mv tools/verdict-back-ends/STEM extern
        mkdir extern/examples
        mv models/CASE_Toy_Models extern/examples
        mv models/DeliveryDrone_CASE_v* extern/examples
        chmod a+x extern/{mac,nix}/{aadl2iml,kind2,soteria_pp}
        cp -a tools/verdict-back-ends/verdict-bundle/verdict-bundle-app/target/verdict-bundle-app-*-capsule.jar extern
        zip -r extern.zip extern
        mkdir tools/verdict-back-ends/{aadl2iml,soteria_pp}/bin
        cp -a extern/nix/aadl2iml tools/verdict-back-ends/aadl2iml/bin
        cp -a extern/nix/soteria_pp tools/verdict-back-ends/soteria_pp/bin

    - name: Upload extern.zip to GitHub release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: extern.zip
        asset_name: extern.zip
        asset_content_type: application/zip

    - name: Upload README.md to GitHub release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: docs/README.md
        asset_name: README.md
        asset_content_type: text/markdown; charset=UTF-8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push verdict image
      uses: docker/build-push-action@v2
      with:
        context: tools/verdict-back-ends
        file: tools/verdict-back-ends/Dockerfile
        push: true
        cache-from: type=registry,ref=gehighassurance/verdict-dev:latest
        cache-to: type=inline
        tags: |
          gehighassurance/verdict:latest
          gehighassurance/verdict:${{ github.event.release.tag_name }}

    - name: Check out VERDICT-update-sites
      uses: actions/checkout@v2
      with:
        repository: ge-high-assurance/VERDICT-update-sites
        token: ${{ secrets.CI_PAT }}
        path: VERDICT-update-sites

    - name: Update verdict-latest in VERDICT-update-sites
      run: |
        RELEASE="${{ github.event.release.tag_name }}"
        cd VERDICT-update-sites
        rm -rf verdict-latest verdict-$RELEASE
        mv ../tools/verdict/com.ge.research.osate.verdict.updatesite/target/repository verdict-latest
        cp -a verdict-latest verdict-$RELEASE
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update verdict-latest and verdict-$RELEASE in VERDICT-update-sites"
        git push
